### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by WillTechRelate** [sjkingo/python-freshdesk#1]
Hi,

When running a simple call to list_open_tickets I get the following error

Traceback (most recent call last):
  File "C:/Install/Dev/Freshdesk1.py", line 4, in <module>
    a.tickets.list_open_tickets()
  File "C:\Python34\lib\site-packages\freshdesk\api.py", line 50, in list_open_tickets
    return self.list_tickets(filter_name='new_my_open')
  File "C:\Python34\lib\site-packages\freshdesk\api.py", line 42, in list_tickets
    return [self.get_ticket(t['display_id']) for t in tickets]
  File "C:\Python34\lib\site-packages\freshdesk\api.py", line 42, in <listcomp>
    return [self.get_ticket(t['display_id']) for t in tickets]
  File "C:\Python34\lib\site-packages\freshdesk\api.py", line 13, in get_ticket
    return Ticket(**self._api._get(url)['helpdesk_ticket'])
  File "C:\Python34\lib\site-packages\freshdesk\models.py", line 12, in __init__
    self.created_at = self._to_timestamp(self.created_at)
  File "C:\Python34\lib\site-packages\freshdesk\models.py", line 19, in _to_timestamp
    return datetime.datetime.strptime(timestamp_str, '%Y-%m-%dT%H:%M:%S+10:00')
  File "C:\Python34\lib\_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "C:\Python34\lib\_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '2015-01-07T20:03:25+00:00' does not match format '%Y-%m-%dT%H:%M:%S+10:00'

It looks like the code doesn't handle any timezones other than +10:00, can this be looked at please?

Thanks
Will

**Comment by sjkingo** [comment]
This is an interesting problem as the `strptime()` function doesn't natively support timezones, since their formatting can be quite ambiguous. `%z` *should* work on POSIX systems, however you're using Windows which probably means it won't work.

I agree though it can't be hard coded, so we may have to look at adding a new dependency in `dateutil`, which has handling for this sort of thing.

I will have a look and see what I can come up with.

**Comment by WillTechRelate** [comment]
I did play around with it to get working.  It looked to me like the error was down to an additional : between hours and minutes in the timezone being returned.

I stripped that out in models.py with the below

    def _to_timestamp(self, timestamp_str):
        """Converts a timestamp string as returned by the API to
        a native datetime object and return it."""
        timestamp_str = timestamp_str[:-3]
        timestamp_str += '00'
        return datetime.datetime.strptime(timestamp_str, '%Y-%m-%dT%H:%M:%S%z')


All then worked for me, but I’m not sure if that is correct for other OS’es.  It’s the first time I’ve been looking at python in 5 years, so a little rusty.

Kind Regards
Will

**Comment by sjkingo** [comment]
Hmm it seems in Python 3 the `%z` method is guaranteed to work - I hadn't realised. No such guarantee on Python 2 so I would definitely want to test more with that. Also be careful, as you are stripping off the minutes in the timezone; it is perfectly valid to have a +09:30 etc.

**Comment by sjkingo** [comment]
Can you try updating to 0.9.3 (I just pushed it to PyPi) - this should fix the problems for you :)

**Comment by WillTechRelate** [comment]
Yes, that works great.   Thanks
