### ISSUE TITLE
`FreshdeskModel._keys` set is shared between different submodels

### ISSUE THREAD

**Issue by aomelianenko** [sjkingo/python-freshdesk#21]
In the code there is a base class `FreshdeskModel` and submodels like `Ticket` or `Group` etc. In the base class the keys from JSON are stored into `_keys` set, but the problem is that this set is shared on base class level, i.e. singleton. So whenever you work with multiple models and access the `_keys` collection it will contain all keys from all models.

Steps to reproduce (example):
1) Query for ticket(s)
2) Query for contact(s)
3) Access `_keys` collection from any of the models
=> it contains keys from both tickets and contact

**Comment by sjkingo** [comment]
Great catch, it should be fixed by moving the initialisation of `_keys` into the `__init__()` method instead of class declaration. I'll fix that today.

**Comment by sjkingo** [comment]
I've just released version 1.2.1 on pypi that includes this fix. Thanks!
