### ISSUE TITLE
Add contributor access

### ISSUE THREAD

**Issue by sjkingo** [sjkingo/python-freshdesk#23]
@prenit-coverfox: would you like me to add contributor access to the repo for you, so you can push changes directly into master + release on pypi?

I don't use freshdesk anymore and don't really have the time to review and merge changes.

I'd be happy if you wanted to do that?

**Comment by prenit-coverfox** [comment]
Hello.
I would very much like that. We are using freshdesk at our organization and want to extend the support for the product. I would take this opportunity to continue my contribution to the repo and maintain it. Thank you.

Regards
Prenit Wankhede

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sjkingo** [comment]
Awesome, thanks for that. I have added you as a collaborator which gives you full push access to the repo.

If you give me your pypi username I can do the same there.

My usual release process is to update the changelog, version bump (I use semver) and then upload to pypi both the source dist and binary wheel (`python3 setup.py sdist bdist_wheel upload`) and also make a Github release. If you could follow that process that would be great.

**Comment by sjkingo** [comment]
I've added prenit-wankhede to the pypi project. Thanks!
