### ISSUE TITLE
Filtername can be unset by default

### ISSUE THREAD

**Issue by sjortiz** [sjkingo/python-freshdesk#27]
# Feature requests

## Preface 

On this line it implicitly sets `filter_name = 'new_and_my_open'`
https://github.com/sjkingo/python-freshdesk/blob/master/freshdesk/v2/api.py#L72
which is not actually required, and depending on uses cases we would want all the tickets.

## Request

Could you consider removing it?

**Comment by sjkingo** [comment]
I don't think changing this would be a good idea as there may be projects relying on the current behaviour.

You can simply pass `filter_name=None` to `list_tickets()` if you wish to return all tickets:

```python
print(api.tickets.list_tickets(filter_name=None))
```

Perhaps we could update the docs to better explain this functionality?

**Comment by sjortiz** [comment]
Understood, can we update the docs? I don't mind doing a PR to update the docs, anyway, this cool a breaking change if you want to do it any time later, with previous advice.

**Comment by sjkingo** [comment]
A PR for the docs would be great, thanks!

**Comment by prenit-coverfox** [comment]
I will update the readme file. Closing this issue.
