### ISSUE TITLE
Getting Ticket Description

### ISSUE THREAD

**Issue by brown2D** [sjkingo/python-freshdesk#49]
Hello, 

Thank you so much for developing this code! I've found it tremendously useful in my daily work. However, I am having an issue with pulling the 'description' and 'description_text' using the code. All other fields work just fine. Could this have to do with the update of the parameter "include" to pull these in the API? Is there a workaround for this?

**Comment by brown2D** [comment]
solved!

**Comment by sjkingo** [comment]
Great, what was the issue you had? Maybe we can make something easier or update the docs if it's a pain point.

**Comment by codepypl** [comment]
to get ticket description you need to go to particular ticket  like this :
`
for ticket in fresh_api.tickets.list_new_and_my_open_tickets():
    {fresh_api.tickets.get_ticket(ticket.id).description_text}
`

It would be more clear if we could do : 
`
for ticket in fresh_api.tickets.list_new_and_my_open_tickets():
    {ticket.description_text}
`
