### ISSUE TITLE
Feature Request: Get back ticket ID after ticket creation

### ISSUE THREAD

**Issue by SimWhite** [sjkingo/python-freshdesk#68]
Hi. It's not an issue just a feature request.

It would be great to get back ticket Id when it was created.
So we can work with ticket URL to send it back to the creator for example.

**Comment by sjkingo** [comment]
Hi, `create_ticket` returns a new `Ticket` instance, so you should be able to access the `.id` property of the return.

Does this work for you?

**Comment by SimWhite** [comment]
Yep, thanks a lot!
