### ISSUE TITLE
Can't get requester name

### ISSUE THREAD

**Issue by codepypl** [sjkingo/python-freshdesk#71]
Ticket.name does not exist (official freshdesk api has this property)
I also can't use ticket.contacts.get_contact(id)
because it rises exception 'Freshdesk not found' why ?

**Comment by sjkingo** [comment]
Can you please paste in the full exception including traceback that you're getting? Thanks

**Comment by codepypl** [comment]
1.
`

            Freshdesk has deprecated their V1 API from 1st July, 2018.
            For more info, visit https://support.freshdesk.com/support/solutions/articles/231955-important-deprecation-of-api-v1
            
            For more info about freshdesk V2 API, visit https://developers.freshdesk.com/api/
            
            Now python-freshdesk library will by default return V2 API client. You need to migrate your project accordingly.
            
            
        
(env) ➜  DiscordBot python3 fresh.py 

            Freshdesk has deprecated their V1 API from 1st July, 2018.
            For more info, visit https://support.freshdesk.com/support/solutions/articles/231955-important-deprecation-of-api-v1
            
            For more info about freshdesk V2 API, visit https://developers.freshdesk.com/api/
            
            Now python-freshdesk library will by default return V2 API client. You need to migrate your project accordingly.
            
            
        
Traceback (most recent call last):
  File "/Volumes/Dane/Projekty/DiscordBot/fresh.py", line 9, in <module>
    print(ticket.name)
AttributeError: 'Ticket' object has no attribute 'name'

simple for loop :

for ticket in f.tickets.list_new_and_my_open_tickets():
    print(ticket.name)

`

2.

**Comment by codepypl** [comment]
fixed by getting the name from ticket view
the question is how to handle errors ?
