### ISSUE TITLE
ModuleNotFoundError: No module named 'freshdesk.api'; 'freshdesk' is not a package

### ISSUE THREAD

**Issue by sherodkeen** [sjkingo/python-freshdesk#77]
I just pip installed python-freshdesk and tried to import the module, but am getting this error. 

_ModuleNotFoundError: No module named 'freshdesk.api'; 'freshdesk' is not a package_

**Python Code that recieved the above error:**

from freshdesk.api import API
a = API('XXXXXXX.freshdesk.com', 'XXXXXXXXXXXXXXX')
tickets = a.tickets.list_tickets()
print(tickets)

**Comment by sjkingo** [comment]
Glad you got it working!
