### ISSUE TITLE
Pass HTTPError correctly for handling rate limits.

### ISSUE THREAD

**Issue by paul-hansen** [sjkingo/python-freshdesk#9]
The way [this code](https://github.com/sjkingo/python-freshdesk/blob/0e254d32924ec7cee0fc522b67f667df19a6eadc/freshdesk/v2/api.py#L187-L190) is written makes it hard to get at the error code and headers. Freshdesk's [best practices](http://developers.freshdesk.com/api/#best_practices) state you should queue API calls and if they hit the rate limit it will return error code [429](http://developers.freshdesk.com/api/#error) and will return a header with the name ["Retry-After"](http://developers.freshdesk.com/api/#ratelimit) that contains the number of seconds until you should try again.

[api.py L187-190](https://github.com/sjkingo/python-freshdesk/blob/0e254d32924ec7cee0fc522b67f667df19a6eadc/freshdesk/v2/api.py#L187-L190) 
``` python
try:
   req.raise_for_status()
except Exception as e:
   raise HTTPError("{}: {}".format(e, j))
```

Is essentially catching all exceptions and turning them into a new HTTPError with the error info stuffed into a formatted string as the error's message. It does not preserve the original error information so when I try to do this:
``` python
try:
   ticket = api.tickets.create_ticket(...)
except HTTPError as e:
   print e.response.status_code 
#raised unexpected: AttributeError("'NoneType' object has no attribute 'status_code'",)
```
The status code has not been set.

My solution was to just remove the try/except from your code so I am able to handle the actual error myself, then the above code works and I can also use `e.response.headers["Retry-After"]` to get the time to wait to try again.

If you actually need to add more information to the error, the discussions here might help with understanding more on how raising an HTTPError should work :
http://stackoverflow.com/questions/6174560/reraise-httperror-with-extra-info
http://stackoverflow.com/questions/33478661/how-to-raise-httperror
The Requests module already passes an HTTPError though so I don't see the need to try to catch that exception as it is something that should be handled outside of your library.

**Comment by sjkingo** [comment]
You're right - this is bad practice on my part! Happy to accept a PR with your changes.
